### YamlMime:TSEnum
name: CustomFunctions.ErrorCode
uid: custom-functions-runtime!CustomFunctions.ErrorCode:enum
package: custom-functions-runtime!
fullName: CustomFunctions.ErrorCode
summary: >-
  Códigos de error para funciones personalizadas. Los códigos de error aparecerán en la celda que invocó la función.


  Los mensajes de error personalizados aparecen además de estos códigos de error. Los mensajes personalizados se muestran en el menú indicador de error, al que se accede al mantener el puntero sobre la marca de error en cada celda con un error.
remarks: ''
isPreview: false
isDeprecated: false
fields:
- name: divisionByZero
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que la función usada se divide entre celdas cero o vacías. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#DIV/0!\""
- name: invalidName
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que hay un error tipográfico en el nombre de la función. Tenga en cuenta que este código de error se admite como un error de entrada de función personalizada, pero no como un error de salida de función personalizada. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NAME?\""
- name: invalidNumber
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que hay un problema con un número en la función. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NUM!\""
- name: invalidReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que la función hace referencia a una celda no válida. Tenga en cuenta que este código de error se admite como un error de entrada de función personalizada, pero no como un error de salida de función personalizada. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#REF!\""
- name: invalidValue
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que un valor de la función es del tipo de datos incorrecto. Se puede usar un mensaje de error personalizado además del código de error, si lo desea. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#VALUE!\""
- name: notAvailable
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que la función o el servicio no están disponibles. Se puede usar un mensaje de error personalizado además del código de error, si lo desea. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#N/A\""
- name: nullReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que los intervalos de la función no se cruzan. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1.3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NULL!\""
metadata:
  ms.openlocfilehash: 2c8673b5e49abbb312138d3436da25613d17df74
  ms.sourcegitcommit: a8a86cfcaff5ad7dacc653d63502c76b1fedbebe
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 03/26/2021
  ms.locfileid: "51236111"
