### YamlMime:TSEnum
name: CustomFunctions.ErrorCode
uid: custom-functions-runtime!CustomFunctions.ErrorCode:enum
package: custom-functions-runtime!
fullName: CustomFunctions.ErrorCode
summary: >-
  Códigos de error de las funciones personalizadas. Los códigos de error aparecerán en la celda que invocó la función.


  Aparecen mensajes de error personalizados además de estos códigos de error. Los mensajes personalizados se muestran en el menú indicador de error, al que se tiene acceso al mantener el puntero sobre el indicador de error en cada celda con un error.
remarks: ''
isPreview: false
isDeprecated: false
fields:
- name: divisionByZero
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.divisionByZero:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que la función usada está dividiendo por cero o celdas vacías. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#DIV/0!\""
- name: invalidName
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidName:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que hay un error tipográfico en el nombre de la función. Tenga en cuenta que este código de error se admite como un error de entrada de función personalizada, pero no como un error de salida de función personalizada. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NAME?\""
- name: invalidNumber
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidNumber:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que hay un problema con un número en la función. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NUM!\""
- name: invalidReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidReference:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que la función hace referencia a una celda no válida. Tenga en cuenta que este código de error se admite como un error de entrada de función personalizada, pero no como un error de salida de función personalizada. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#REF!\""
- name: invalidValue
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.invalidValue:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que un valor de la función es del tipo de datos incorrecto. Si lo desea, puede usar un mensaje de error personalizado además del código de error. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#VALUE!\""
- name: notAvailable
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.notAvailable:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que la función o el servicio no está disponible. Si lo desea, puede usar un mensaje de error personalizado además del código de error. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#N/A\""
- name: nullReference
  uid: custom-functions-runtime!CustomFunctions.ErrorCode.nullReference:member
  package: custom-functions-runtime!
  summary: 'Este código de error indica que los intervalos de la función no se entrecruzan. No se puede usar un mensaje de error personalizado. \[[Conjunto de API: CustomFunctionsRuntime 1,3](/office/dev/add-ins/excel/custom-functions-requirement-sets)\]'
  value: "\"#NULL!\""
metadata:
  ms.openlocfilehash: cec80f674bc573e3e3d3679ab96792ea5e469ce3
  ms.sourcegitcommit: a6ecbc9abca2ab5c82af4c869e3e2d72c999a4c1
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 12/02/2020
  ms.locfileid: "49547344"
